export const CALL_API_GET_DATA = "CALL_API_GET_DATA";
export const CALL_API_UPDATE_STATE= "CALL_API_UPDATE_STATE";
export const HANDLE_INPUT = "HANDLE_INPUT"
export const CALL_API_CREATE ="CALL_API_CREATE"
export const CALL_API_FOR_DELETE = "CALL_API_FOR_DELETE"
export const HANDLE_EDITING = "HANDLE_EDITING"
export const CALL_API_FINISH_EDITING="CALL_API_FINISH_EDITING"